ControleDeEstoque/Controllers/Cadastro/CadUsuarioController.cs
using ControleDeEstoque.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ControleDeEstoque.Controllers
{
    [Authorize(Roles = "Gerente")]
    public class CadUsuarioController:Controller
    {
       private const string _senhaPadrao = "{$1300,$1900}";
       private const int _quantMaxLinhasPorPagina = 5;

        [Authorize] // tornando  privado metudo 
        public ActionResult Index() // vem tudo da index.cshtml aproveitando o codigo de cadastro 
        {
            
            ViewBag.SenhaPadrao = _senhaPadrao;
            ViewBag.ListaTamPag = new SelectList(new int[] { _quantMaxLinhasPorPagina, 10, 15, 20 }, _quantMaxLinhasPorPagina); // criando dropdowlist
            ViewBag.QuantMaxLinhasPorPagina = _quantMaxLinhasPorPagina;
            ViewBag.PaginaAtual = 1;

            var lista = UsuarioModel.RecuperarLista(ViewBag.PaginaAtual, _quantMaxLinhasPorPagina);
            var quant = GrupoProdutoModel.RecuperarQuantidade();

            var difQuantPaginas = (quant % ViewBag.QuantMaxLinhasPorPagina) > 0 ? 1 : 0;
            ViewBag.QuantPaginas = (quant / ViewBag.QuantMaxLinhasPorPagina) + difQuantPaginas; ; // estou fazendo uma divisão da pagina e linhas 

            return View(lista);
        }

        [HttpPost]
        
        [ValidateAntiForgeryToken]
        public JsonResult UsuarioPagina(int pagina, int tamPag)
        {
            var lista = UsuarioModel.RecuperarLista(pagina, tamPag);// fazendo a logica da paginação 

            return Json(lista);

        }

        [HttpPost]
        
        [ValidateAntiForgeryToken] //evitando ataque de cruzamento CSRF
        public ActionResult RecuperarUsuario(int id)
        {
            return Json(UsuarioModel.RecuperarPeloId(id));
        }

        [HttpPost]
        
        [ValidateAntiForgeryToken]
        public ActionResult ExcluirUsuario(int id)
        {

            return Json(UsuarioModel.ExcluirPeloId(id));
        }


        [HttpPost]
        
        [ValidateAntiForgeryToken]
        public ActionResult SalvarUsuario(UsuarioModel model)
        {
            var resultado = "OK";
            var mensagens = new List<string>();
            var idSalvo = string.Empty;

            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagens = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    if (model.Senha == _senhaPadrao)
                    {
                        model.Senha = "";
                    }
                    var id = model.Salvar();
                    if (id > 0)
                    {
                        idSalvo = id.ToString();
                    }
                    else
                    {
                        resultado = "ERRO";
                    }
                }
                catch (Exception ex)
                {
                    resultado = "ERRO";
                }
            }

            return Json(new { Resultado = resultado, Mensagens = mensagens, IdSalvo = idSalvo });
        }
       
    }
}

ControleDeEstoque/Views/CadUsuario/Index.cshtml
@model List<ControleDeEstoque.Models.UsuarioModel>
@{
    Layout = "~/Views/Shared/_Cadastro.cshtml"; // HErdando de cadastro.cshtml
    ViewBag.Title = "Usuário";
    ViewBag.Lista = Model;
}
@section Styles{
    <link href="~/Content/bootstrap-select.css" rel="stylesheet" />
    <link href="~/Content/Cadastro/Usuario.css" rel="stylesheet" />
}

@section TituloGrid{

    <th>Nome</th>
    <th>Login</th>
    <th>Ação</th>
}

@section LinhaGrid{
    @{
        var linha = 0;
        foreach (var item in Model)
        {
            linha++;
            if (linha <= ViewBag.QuantMaxLinhasPorPagina)
            {
                <tr data-id="@item.Id">
                    <td>@item.Nome</td>
                    <td>@item.Login</td>
                    

                    <td>
                        <a class="btn btn-primary btn-alterar" role="button"><i class="glyphicon glyphicon-pencil"></i> Alterar</a>
                        <a class="btn btn-danger btn-excluir" role="button"><i class="glyphicon glyphicon-trash"></i> Excluir</a>
                    </td>
                </tr>
            }
            else
            {
                break;
            }
        }
    }
}

@section CamposCadastro{
    <div class="row">
        <div class="form-group">
            @Html.Label("txt_nome", "Nome", new { @class = "col-md-2 col-form-label text-right" })
            <div class="col-md-6">
                @Html.TextBox("txt_nome", null, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("txt_login", "Login", new { @class = "col-md-2 col-form-label text-right" })
            <div class="col-md-6">
                @Html.TextBox("txt_login", null, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("txt_senha", "Senha", new { @class = "col-md-2 col-form-label text-right" })
            <div class="col-md-6">
                @Html.TextBox("txt_senha", null, new { @class = "form-control", type = "password" })
            </div>
        </div>
       
    </div>
}
@section Scripts{
    <script src="~/Scripts/bootstrap-select.js"></script>
    <script>
       var tituloPagina = '@ViewBag.Title'; // o titulo vem da controller
       var url_excluir = '@Url.Action("ExcluirUsuario", "CadUsuario")';
       var url_confirmar = '@Url.Action("SalvarUsuario", "CadUsuario")';
       var url_page_click = '@Url.Action("UsuarioPagina", "CadUsuario")';
       var url_tam_pag_change = '@Url.Action("UsuarioPagina", "CadUsuario")';
       var url_alterar = '@Url.Action("RecuperarUsuario", "CadUsuario")';
    </script>
    <script src="~/Scripts/Cadastro/Usuario.js"></script>
}